/**
 * IP Protection Utilities
 * Copyright © 2025 hA.I.r. All Rights Reserved.
 * Proprietary and Confidential
 */

export const COPYRIGHT_NOTICE = "© 2025 hA.I.r. All Rights Reserved. Proprietary Software.";

/**
 * Adds watermark to AI-generated content
 */
export const watermarkContent = (content: string, userId?: string): string => {
  const timestamp = new Date().toISOString();
  const id = userId ? ` | User: ${userId.slice(0, 8)}` : "";
  return `${content}\n\n---\n*Generated by hA.I.r™ on ${timestamp}${id}*`;
};

/**
 * Detects suspicious activity patterns
 */
export const detectSuspiciousActivity = (): boolean => {
  // Check for dev tools
  const isDevTools = /./;
  isDevTools.toString = function() {
    return "DevTools detected";
  };
  
  // Check for automated access patterns
  const isAutomated = navigator.webdriver || 
                      (window as any).__nightmare || 
                      (window as any).phantom;
  
  return !!isAutomated;
};

/**
 * Console protection
 */
export const protectConsole = () => {
  if (process.env.NODE_ENV === 'production') {
    const noop = () => {};
    const methods = ['log', 'debug', 'info', 'warn', 'error'] as const;
    
    methods.forEach(method => {
      console[method] = noop;
    });
  }
};

/**
 * Add copyright notice to console
 */
export const addCopyrightNotice = () => {
  const style = 'color: #ef4444; font-size: 16px; font-weight: bold;';
  const message = `
%c⚠️ WARNING ⚠️

This is proprietary software owned by hA.I.r.
Copyright © 2025. All Rights Reserved.

Unauthorized access, copying, or reverse engineering is:
• Strictly prohibited
• Monitored and logged
• Subject to legal prosecution

If you're interested in licensing or partnership:
Contact us through official channels.
`;
  
  console.log(message, style);
};

/**
 * Disable right-click context menu (optional - can be annoying to users)
 */
export const disableRightClick = (enable: boolean = true) => {
  if (enable && process.env.NODE_ENV === 'production') {
    document.addEventListener('contextmenu', (e) => {
      e.preventDefault();
      return false;
    });
  }
};

/**
 * Disable text selection on proprietary elements
 */
export const protectElement = (element: HTMLElement) => {
  element.style.userSelect = 'none';
  element.style.webkitUserSelect = 'none';
  element.setAttribute('unselectable', 'on');
};

/**
 * Obfuscate sensitive data in logs
 */
export const obfuscate = (data: string): string => {
  if (data.length <= 4) return '****';
  return data.slice(0, 2) + '*'.repeat(data.length - 4) + data.slice(-2);
};

/**
 * Generate unique fingerprint for tracking
 */
export const generateFingerprint = async (): Promise<string> => {
  const data = [
    navigator.userAgent,
    navigator.language,
    screen.colorDepth,
    screen.width,
    screen.height,
    new Date().getTimezoneOffset(),
    navigator.hardwareConcurrency,
  ].join('|');
  
  const encoder = new TextEncoder();
  const dataBuffer = encoder.encode(data);
  const hashBuffer = await crypto.subtle.digest('SHA-256', dataBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
};

/**
 * Log suspicious activity
 */
export const logSuspiciousActivity = async (activity: string, details?: any) => {
  const fingerprint = await generateFingerprint();
  
  console.error('🚨 SECURITY ALERT:', {
    activity,
    fingerprint,
    timestamp: new Date().toISOString(),
    details,
  });
  
  // In production, you could send this to your backend for monitoring
  // fetch('/api/security-log', { method: 'POST', body: JSON.stringify(...) })
};
