import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.7.1";
import { z } from "https://deno.land/x/zod@v3.22.4/mod.ts";

/**
 * Copyright © 2025 hA.I.r. All Rights Reserved.
 * Proprietary AI Formula Generation System
 */

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Input validation schema
const requestSchema = z.object({
  hairDescription: z.string().min(10).max(2000),
  colorLine: z.string().max(255).optional(),
  clientNotes: z.string().max(1000).optional(),
  imageAnalysis: z.string().max(5000).optional(),
});

// Watermark helper
const addWatermark = (content: string, userId?: string): string => {
  const timestamp = new Date().toISOString().split('T')[0];
  return `${content}\n\n---\n*Generated by hA.I.r™ Proprietary AI System on ${timestamp}${userId ? ' | User: ' + userId.slice(0, 8) : ''} | This formula is confidential and proprietary.*`;
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const body = await req.json();
    
    // Validate input
    const validationResult = requestSchema.safeParse(body);
    if (!validationResult.success) {
      return new Response(
        JSON.stringify({ 
          error: 'Invalid input', 
          details: validationResult.error.issues.map(i => i.message).join(', ')
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }
    
    const { hairDescription, colorLine, clientNotes, imageAnalysis } = validationResult.data;
    
    // Get authorization header to extract user ID
    const authHeader = req.headers.get('authorization');
    let userId: string | undefined;
    
    if (authHeader) {
      try {
        const token = authHeader.replace('Bearer ', '');
        const payload = JSON.parse(atob(token.split('.')[1]));
        userId = payload.sub;
      } catch (e) {
        console.log('Could not extract user ID from token');
      }
    }
    
    const LOVABLE_API_KEY = Deno.env.get('LOVABLE_API_KEY');
    if (!LOVABLE_API_KEY) {
      throw new Error('LOVABLE_API_KEY is not configured');
    }

    const systemPrompt = `You are a master hair colorist with 20+ years of experience specializing in ${colorLine || 'professional hair color'}. 
Your task is to provide 2-3 detailed hair color formulas with step-by-step instructions.

IMPORTANT: These formulas are SUGGESTIONS only. Hair color results can vary significantly based on individual hair chemistry, porosity, previous treatments, and other factors. Always recommend a strand test and patch test before full application.

Format your response as a JSON array with this structure:
[
  {
    "formula_name": "Formula Option 1",
    "formula_text": "Detailed formula with exact measurements (e.g., 30g 7N + 60ml 20vol developer)",
    "instructions": "Step-by-step instructions numbered 1-10",
    "processing_time": "30-45 minutes",
    "expected_result": "Description of expected color result",
    "difficulty": "beginner/intermediate/advanced"
  }
]

Consider:
- Hair condition and health
- Natural hair level and undertones
- Desired result vs realistic outcome
- Application technique
- Safety and patch test recommendations`;

    const userPrompt = `Client hair description: ${hairDescription}
${imageAnalysis ? `Hair photo analysis: ${imageAnalysis}` : ''}
${clientNotes ? `Additional notes: ${clientNotes}` : ''}

Please provide 2-3 formula options with complete instructions.`;

    console.log('Calling AI Gateway for formula generation...');
    
    const response = await fetch('https://ai.gateway.lovable.dev/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${LOVABLE_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        max_tokens: 3000,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error('AI Gateway error:', response.status, errorText);
      
      if (response.status === 429) {
        return new Response(
          JSON.stringify({ error: 'Rate limit exceeded. Please try again in a moment.' }),
          { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      if (response.status === 402) {
        return new Response(
          JSON.stringify({ error: 'AI usage limit reached. Please add credits to continue.' }),
          { status: 402, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      throw new Error(`AI Gateway error: ${response.status}`);
    }

    const data = await response.json();
    console.log('AI response received');
    
    const aiContent = data.choices[0].message.content;
    
    // Try to parse JSON from the response
    let formulas;
    try {
      // Extract JSON array from markdown code blocks if present
      const jsonMatch = aiContent.match(/```json\n?([\s\S]*?)\n?```/) || aiContent.match(/\[([\s\S]*)\]/);
      const jsonString = jsonMatch ? (jsonMatch[1] || jsonMatch[0]) : aiContent;
      formulas = JSON.parse(jsonString);
      
      // Add watermark to each formula
      formulas = formulas.map((formula: any) => ({
        ...formula,
        formula_text: addWatermark(formula.formula_text, userId),
      }));
    } catch (parseError) {
      console.error('JSON parse error:', parseError);
      // If JSON parsing fails, return the raw content with watermark
      formulas = [{
        formula_name: "AI Generated Formula",
        formula_text: addWatermark(aiContent, userId),
        instructions: "See formula text for details",
        processing_time: "30-45 minutes",
        expected_result: "Professional color result",
        difficulty: "intermediate"
      }];
    }

    return new Response(
      JSON.stringify({ formulas }),
      { 
        status: 200, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  } catch (error: any) {
    console.error('Error in generate-formula function:', error);
    return new Response(
      JSON.stringify({ error: error.message || 'An unexpected error occurred' }),
      { 
        status: 500, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    );
  }
});
