/**
 * AI Disclaimer Component
 * LEGAL PROTECTION: Limits liability for AI-generated recommendations
 */

import { Sparkles } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

interface AIDisclaimerProps {
  context?: "formula" | "chat" | "recommendation" | "general";
  className?: string;
}

export const AIDisclaimer = ({ context = "general", className = "" }: AIDisclaimerProps) => {
  const disclaimers = {
    formula: {
      title: "AI Formula Disclaimer",
      description: "This formula was generated by artificial intelligence based on the information provided. It is for reference only and should be verified by a licensed professional. Always perform strand tests and patch tests before applying any formula. Individual results may vary significantly."
    },
    chat: {
      title: "AI Assistant Notice",
      description: "This AI assistant provides general hair care information and suggestions. It is not a substitute for professional cosmetology advice. For complex situations, color corrections, or chemical treatments, always consult a licensed hair professional."
    },
    recommendation: {
      title: "AI Recommendations",
      description: "Product and technique recommendations are AI-generated based on general information. Individual hair types, conditions, and reactions vary. Always verify recommendations with a licensed professional before use. We are not liable for results."
    },
    general: {
      title: "AI-Powered Features",
      description: "This platform uses artificial intelligence to assist with styling recommendations and information. AI suggestions are informational only and not professional advice. Always verify AI-generated content with licensed professionals. Individual results may vary. Use at your own discretion."
    }
  };

  const { title, description } = disclaimers[context];

  return (
    <Alert variant="default" className={`border-primary/50 bg-primary/5 ${className}`}>
      <Sparkles className="h-4 w-4 text-primary" />
      <AlertTitle className="text-primary font-semibold">{title}</AlertTitle>
      <AlertDescription className="text-muted-foreground text-sm mt-2">
        {description}
      </AlertDescription>
    </Alert>
  );
};
